name: testworkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    -name: step1
      run: echo "This is a first step of workflow"
    -name: step2
      run: echo "This is a second step of workflow"    